class RegistrationPage_OR():
    rdo_Gender_Male = "//input[@id='gender-male']"
    rdo_Gender_Female = "//input[@id='gender-female']"
    edi_FirstName = "//input[@id='FirstName']"
    edi_LastName = "//input[@id='LastName']"
    drp_Day = "//select[@name='DateOfBirthDay']"
    drp_Month = "//select[@name='DateOfBirthMonth']"
    drp_Year = "//select[@name='DateOfBirthYear']"
    edi_Email = "//input[@id='Email']"
    edi_Password = "//input[@id='Password']"
    edi_cnfPassword = "//input[@id='ConfirmPassword']"
